export const CategoryActionTypes = {
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    ADD_CATEGORY: 'ADD_CATEGORY',
    EDIT_CATEGORY: 'EDIT_CATEGORY',
    CANCEL_EDIT_CATEGORY: 'CANCEL_EDIT_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    LOAD_CATEGORIES_FINISHED: 'LOAD_CATEGORIES_FINISHED'
};

export const FilterActionTypes = {
    LOAD_FILTERS: 'LOAD_FILTERS',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    GET_QUERY: 'GET_QUERY',
    UPDATE_QUERY: 'UPDATE_QUERY',
    SAVE_FILTERS: 'SAVE_FILTERS'
};