export const CategoryActionTypes = {
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    ADD_CATEGORY: 'ADD_CATEGORY',
    EDIT_CATEGORY: 'EDIT_CATEGORY',
    CANCEL_EDIT_CATEGORY: 'CANCEL_EDIT_CATEGORY',
    TOGGLE_CATEGORY: 'TOGGLE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY'
};

export const FilterActionTypes = {
    LOAD_FILTER: 'LOAD_FILTER',
    GET_QUERY: 'GET_QUERY',
    SAVE_FILTER: 'SAVE_FILTER'
};